/*
* generated by Xtext
*/
package com.dexels.navajo.dsl.tsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.dexels.navajo.dsl.tsl.ui.internal.TslActivator.getInstance().getInjector("com.dexels.navajo.dsl.tsl.Tsl");
	}
	
}
