/*
 * generated by Xtext
 */
package com.dexels.navajo.dsl.tsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.dexels.navajo.dsl.tsl.ui.internal.TslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TslActivator.getInstance().getInjector(TslActivator.COM_DEXELS_NAVAJO_DSL_TSL_TSL);
	}
	
}
