/*
* generated by Xtext
*/
package com.dexels.navajo.dsl.expression;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class NavajoExpressionUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.dexels.navajo.dsl.expression.ui.internal.NavajoExpressionActivator.getInstance().getInjector("com.dexels.navajo.dsl.expression.NavajoExpression");
	}
	
}
