/*
* generated by Xtext
*/
package com.dexels.navajo.dsl.tsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.dexels.navajo.dsl.tsl.services.TslGrammarAccess;

public class TslParser extends AbstractContentAssistParser {
	
	@Inject
	private TslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser createParser() {
		com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser result = new com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTmlAccess().getAlternatives_2(), "rule__Tml__Alternatives_2");
					put(grammarAccess.getTmlAccess().getAlternatives_4(), "rule__Tml__Alternatives_4");
					put(grammarAccess.getTmlAccess().getAlternatives_4_0_1(), "rule__Tml__Alternatives_4_0_1");
					put(grammarAccess.getAnyContentAccess().getAlternatives(), "rule__AnyContent__Alternatives");
					put(grammarAccess.getNonExpressionAccess().getAlternatives_3_1(), "rule__NonExpression__Alternatives_3_1");
					put(grammarAccess.getMethodsAccess().getAlternatives_2(), "rule__Methods__Alternatives_2");
					put(grammarAccess.getMethodAccess().getAlternatives_3(), "rule__Method__Alternatives_3");
					put(grammarAccess.getValidationsAccess().getAlternatives_2(), "rule__Validations__Alternatives_2");
					put(grammarAccess.getCheckAccess().getAlternatives_3(), "rule__Check__Alternatives_3");
					put(grammarAccess.getCommentClauseAccess().getAlternatives_3(), "rule__CommentClause__Alternatives_3");
					put(grammarAccess.getBreakAccess().getAlternatives_3(), "rule__Break__Alternatives_3");
					put(grammarAccess.getFilePathAccess().getAlternatives(), "rule__FilePath__Alternatives");
					put(grammarAccess.getIncludeAccess().getAlternatives_3(), "rule__Include__Alternatives_3");
					put(grammarAccess.getMessageAccess().getAlternatives_3(), "rule__Message__Alternatives_3");
					put(grammarAccess.getMessageAccess().getAlternatives_3_0_1(), "rule__Message__Alternatives_3_0_1");
					put(grammarAccess.getMapAccess().getAlternatives_4(), "rule__Map__Alternatives_4");
					put(grammarAccess.getMapAccess().getAlternatives_4_1_1(), "rule__Map__Alternatives_4_1_1");
					put(grammarAccess.getRequiredAccess().getAlternatives_3(), "rule__Required__Alternatives_3");
					put(grammarAccess.getPropertyAccess().getCardinalityAlternatives_2_2_2_0(), "rule__Property__CardinalityAlternatives_2_2_2_0");
					put(grammarAccess.getPropertyAccess().getAlternatives_3(), "rule__Property__Alternatives_3");
					put(grammarAccess.getPropertyAccess().getAlternatives_3_1_1(), "rule__Property__Alternatives_3_1_1");
					put(grammarAccess.getParamAccess().getAlternatives_3(), "rule__Param__Alternatives_3");
					put(grammarAccess.getParamAccess().getAlternatives_3_1_1(), "rule__Param__Alternatives_3_1_1");
					put(grammarAccess.getMapMethodAccess().getAlternatives_5(), "rule__MapMethod__Alternatives_5");
					put(grammarAccess.getMapMethodAccess().getAlternatives_5_1_1(), "rule__MapMethod__Alternatives_5_1_1");
					put(grammarAccess.getFieldAccess().getAlternatives_3(), "rule__Field__Alternatives_3");
					put(grammarAccess.getFieldAccess().getAlternatives_3_1_0_1(), "rule__Field__Alternatives_3_1_0_1");
					put(grammarAccess.getDebugTagAccess().getAlternatives_3(), "rule__DebugTag__Alternatives_3");
					put(grammarAccess.getExpressionOrOptionAccess().getAlternatives(), "rule__ExpressionOrOption__Alternatives");
					put(grammarAccess.getExpressionTagAccess().getAlternatives_2(), "rule__ExpressionTag__Alternatives_2");
					put(grammarAccess.getOptionAccess().getAlternatives_3(), "rule__Option__Alternatives_3");
					put(grammarAccess.getAnyExpressionAccess().getAlternatives(), "rule__AnyExpression__Alternatives");
					put(grammarAccess.getPathElementAccess().getAlternatives(), "rule__PathElement__Alternatives");
					put(grammarAccess.getEqualityExpressionAccess().getAlternatives_1(), "rule__EqualityExpression__Alternatives_1");
					put(grammarAccess.getRelationalExpressionAccess().getAlternatives_2(), "rule__RelationalExpression__Alternatives_2");
					put(grammarAccess.getAdditiveExpressionAccess().getAlternatives_1(), "rule__AdditiveExpression__Alternatives_1");
					put(grammarAccess.getMultiplicativeExpressionAccess().getAlternatives_1(), "rule__MultiplicativeExpression__Alternatives_1");
					put(grammarAccess.getUnaryExpressionAccess().getAlternatives(), "rule__UnaryExpression__Alternatives");
					put(grammarAccess.getUnaryExpressionAccess().getAlternatives_0(), "rule__UnaryExpression__Alternatives_0");
					put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getTmlAccess().getGroup(), "rule__Tml__Group__0");
					put(grammarAccess.getTmlAccess().getGroup_3_0(), "rule__Tml__Group_3_0__0");
					put(grammarAccess.getTmlAccess().getGroup_3_1(), "rule__Tml__Group_3_1__0");
					put(grammarAccess.getTmlAccess().getGroup_3_2(), "rule__Tml__Group_3_2__0");
					put(grammarAccess.getTmlAccess().getGroup_3_3(), "rule__Tml__Group_3_3__0");
					put(grammarAccess.getTmlAccess().getGroup_3_4(), "rule__Tml__Group_3_4__0");
					put(grammarAccess.getTmlAccess().getGroup_3_5(), "rule__Tml__Group_3_5__0");
					put(grammarAccess.getTmlAccess().getGroup_3_6(), "rule__Tml__Group_3_6__0");
					put(grammarAccess.getTmlAccess().getGroup_3_7(), "rule__Tml__Group_3_7__0");
					put(grammarAccess.getTmlAccess().getGroup_4_0(), "rule__Tml__Group_4_0__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getNonExpressionAccess().getGroup(), "rule__NonExpression__Group__0");
					put(grammarAccess.getNonExpressionAccess().getGroup_0(), "rule__NonExpression__Group_0__0");
					put(grammarAccess.getNonExpressionAccess().getGroup_3(), "rule__NonExpression__Group_3__0");
					put(grammarAccess.getMethodsAccess().getGroup(), "rule__Methods__Group__0");
					put(grammarAccess.getMethodsAccess().getGroup_2_0(), "rule__Methods__Group_2_0__0");
					put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
					put(grammarAccess.getMethodAccess().getGroup_2(), "rule__Method__Group_2__0");
					put(grammarAccess.getMethodAccess().getGroup_3_0(), "rule__Method__Group_3_0__0");
					put(grammarAccess.getValidationsAccess().getGroup(), "rule__Validations__Group__0");
					put(grammarAccess.getValidationsAccess().getGroup_2_0(), "rule__Validations__Group_2_0__0");
					put(grammarAccess.getCheckAccess().getGroup(), "rule__Check__Group__0");
					put(grammarAccess.getCheckAccess().getGroup_3_0(), "rule__Check__Group_3_0__0");
					put(grammarAccess.getCommentClauseAccess().getGroup(), "rule__CommentClause__Group__0");
					put(grammarAccess.getCommentClauseAccess().getGroup_3_0(), "rule__CommentClause__Group_3_0__0");
					put(grammarAccess.getBreakAccess().getGroup(), "rule__Break__Group__0");
					put(grammarAccess.getBreakAccess().getGroup_3_0(), "rule__Break__Group_3_0__0");
					put(grammarAccess.getIncludeAccess().getGroup(), "rule__Include__Group__0");
					put(grammarAccess.getIncludeAccess().getGroup_2(), "rule__Include__Group_2__0");
					put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
					put(grammarAccess.getMessageAccess().getGroup_2_0(), "rule__Message__Group_2_0__0");
					put(grammarAccess.getMessageAccess().getGroup_2_1(), "rule__Message__Group_2_1__0");
					put(grammarAccess.getMessageAccess().getGroup_2_2(), "rule__Message__Group_2_2__0");
					put(grammarAccess.getMessageAccess().getGroup_2_3(), "rule__Message__Group_2_3__0");
					put(grammarAccess.getMessageAccess().getGroup_2_4(), "rule__Message__Group_2_4__0");
					put(grammarAccess.getMessageAccess().getGroup_3_0(), "rule__Message__Group_3_0__0");
					put(grammarAccess.getMapAccess().getGroup(), "rule__Map__Group__0");
					put(grammarAccess.getMapAccess().getGroup_2(), "rule__Map__Group_2__0");
					put(grammarAccess.getMapAccess().getGroup_3_0(), "rule__Map__Group_3_0__0");
					put(grammarAccess.getMapAccess().getGroup_3_1(), "rule__Map__Group_3_1__0");
					put(grammarAccess.getMapAccess().getGroup_3_2(), "rule__Map__Group_3_2__0");
					put(grammarAccess.getMapAccess().getGroup_3_3(), "rule__Map__Group_3_3__0");
					put(grammarAccess.getMapAccess().getGroup_3_4(), "rule__Map__Group_3_4__0");
					put(grammarAccess.getMapAccess().getGroup_3_5(), "rule__Map__Group_3_5__0");
					put(grammarAccess.getMapAccess().getGroup_4_1(), "rule__Map__Group_4_1__0");
					put(grammarAccess.getMapAccess().getGroup_4_1_3(), "rule__Map__Group_4_1_3__0");
					put(grammarAccess.getRequiredAccess().getGroup(), "rule__Required__Group__0");
					put(grammarAccess.getRequiredAccess().getGroup_2(), "rule__Required__Group_2__0");
					put(grammarAccess.getRequiredAccess().getGroup_3_1(), "rule__Required__Group_3_1__0");
					put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_0(), "rule__Property__Group_2_0__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_1(), "rule__Property__Group_2_1__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_2(), "rule__Property__Group_2_2__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_3(), "rule__Property__Group_2_3__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_4(), "rule__Property__Group_2_4__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_5(), "rule__Property__Group_2_5__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_6(), "rule__Property__Group_2_6__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_7(), "rule__Property__Group_2_7__0");
					put(grammarAccess.getPropertyAccess().getGroup_2_8(), "rule__Property__Group_2_8__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_1(), "rule__Property__Group_3_1__0");
					put(grammarAccess.getParamAccess().getGroup(), "rule__Param__Group__0");
					put(grammarAccess.getParamAccess().getGroup_2_0(), "rule__Param__Group_2_0__0");
					put(grammarAccess.getParamAccess().getGroup_2_1(), "rule__Param__Group_2_1__0");
					put(grammarAccess.getParamAccess().getGroup_2_2(), "rule__Param__Group_2_2__0");
					put(grammarAccess.getParamAccess().getGroup_3_1(), "rule__Param__Group_3_1__0");
					put(grammarAccess.getMapMethodAccess().getGroup(), "rule__MapMethod__Group__0");
					put(grammarAccess.getMapMethodAccess().getGroup_5_1(), "rule__MapMethod__Group_5_1__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getFieldAccess().getGroup_2_0(), "rule__Field__Group_2_0__0");
					put(grammarAccess.getFieldAccess().getGroup_2_1(), "rule__Field__Group_2_1__0");
					put(grammarAccess.getFieldAccess().getGroup_2_2(), "rule__Field__Group_2_2__0");
					put(grammarAccess.getFieldAccess().getGroup_2_3(), "rule__Field__Group_2_3__0");
					put(grammarAccess.getFieldAccess().getGroup_2_4(), "rule__Field__Group_2_4__0");
					put(grammarAccess.getFieldAccess().getGroup_3_1(), "rule__Field__Group_3_1__0");
					put(grammarAccess.getFieldAccess().getGroup_3_1_0(), "rule__Field__Group_3_1_0__0");
					put(grammarAccess.getDebugTagAccess().getGroup(), "rule__DebugTag__Group__0");
					put(grammarAccess.getDebugTagAccess().getGroup_2(), "rule__DebugTag__Group_2__0");
					put(grammarAccess.getDebugTagAccess().getGroup_2_0(), "rule__DebugTag__Group_2_0__0");
					put(grammarAccess.getDebugTagAccess().getGroup_2_1(), "rule__DebugTag__Group_2_1__0");
					put(grammarAccess.getDebugTagAccess().getGroup_3_1(), "rule__DebugTag__Group_3_1__0");
					put(grammarAccess.getExpressionOrOptionAccess().getGroup_0(), "rule__ExpressionOrOption__Group_0__0");
					put(grammarAccess.getExpressionTagAccess().getGroup(), "rule__ExpressionTag__Group__0");
					put(grammarAccess.getExpressionTagAccess().getGroup_1_0(), "rule__ExpressionTag__Group_1_0__0");
					put(grammarAccess.getExpressionTagAccess().getGroup_1_1(), "rule__ExpressionTag__Group_1_1__0");
					put(grammarAccess.getExpressionTagAccess().getGroup_1_2(), "rule__ExpressionTag__Group_1_2__0");
					put(grammarAccess.getExpressionTagAccess().getGroup_2_1(), "rule__ExpressionTag__Group_2_1__0");
					put(grammarAccess.getOptionAccess().getGroup(), "rule__Option__Group__0");
					put(grammarAccess.getOptionAccess().getGroup_3_1(), "rule__Option__Group_3_1__0");
					put(grammarAccess.getTmlExpressionAccess().getGroup(), "rule__TmlExpression__Group__0");
					put(grammarAccess.getTmlExpressionAccess().getGroup_4(), "rule__TmlExpression__Group_4__0");
					put(grammarAccess.getExistsTmlExpressionAccess().getGroup(), "rule__ExistsTmlExpression__Group__0");
					put(grammarAccess.getExistsTmlExpressionAccess().getGroup_5(), "rule__ExistsTmlExpression__Group_5__0");
					put(grammarAccess.getMapReferenceParamsAccess().getGroup(), "rule__MapReferenceParams__Group__0");
					put(grammarAccess.getMapReferenceParamsAccess().getGroup_2(), "rule__MapReferenceParams__Group_2__0");
					put(grammarAccess.getMapGetReferenceAccess().getGroup(), "rule__MapGetReference__Group__0");
					put(grammarAccess.getMapGetReferenceAccess().getGroup_1(), "rule__MapGetReference__Group_1__0");
					put(grammarAccess.getOrExpressionAccess().getGroup(), "rule__OrExpression__Group__0");
					put(grammarAccess.getOrExpressionAccess().getGroup_1(), "rule__OrExpression__Group_1__0");
					put(grammarAccess.getAndExpressionAccess().getGroup(), "rule__AndExpression__Group__0");
					put(grammarAccess.getAndExpressionAccess().getGroup_1(), "rule__AndExpression__Group_1__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup(), "rule__EqualityExpression__Group__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup_1_0(), "rule__EqualityExpression__Group_1_0__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup_1_1(), "rule__EqualityExpression__Group_1_1__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup(), "rule__RelationalExpression__Group__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_2_0(), "rule__RelationalExpression__Group_2_0__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_2_1(), "rule__RelationalExpression__Group_2_1__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_2_2(), "rule__RelationalExpression__Group_2_2__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_2_3(), "rule__RelationalExpression__Group_2_3__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup(), "rule__AdditiveExpression__Group__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup_1_0(), "rule__AdditiveExpression__Group_1_0__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup_1_1(), "rule__AdditiveExpression__Group_1_1__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup(), "rule__MultiplicativeExpression__Group__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1_0(), "rule__MultiplicativeExpression__Group_1_0__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1_1(), "rule__MultiplicativeExpression__Group_1_1__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_0_0(), "rule__UnaryExpression__Group_0_0__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_0_1(), "rule__UnaryExpression__Group_0_1__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_1(), "rule__PrimaryExpression__Group_1__0");
					put(grammarAccess.getFunctionCallAccess().getGroup(), "rule__FunctionCall__Group__0");
					put(grammarAccess.getFunctionCallAccess().getGroup_3(), "rule__FunctionCall__Group_3__0");
					put(grammarAccess.getDateLiteralAccess().getGroup(), "rule__DateLiteral__Group__0");
					put(grammarAccess.getLiteralAccess().getGroup_0(), "rule__Literal__Group_0__0");
					put(grammarAccess.getLiteralAccess().getGroup_2(), "rule__Literal__Group_2__0");
					put(grammarAccess.getLiteralAccess().getGroup_4(), "rule__Literal__Group_4__0");
					put(grammarAccess.getLiteralAccess().getGroup_4_2(), "rule__Literal__Group_4_2__0");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_4_0_1_0(), "rule__Tml__ChildrenAssignment_4_0_1_0");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_4_0_1_1(), "rule__Tml__ChildrenAssignment_4_0_1_1");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_4_0_1_2(), "rule__Tml__ChildrenAssignment_4_0_1_2");
					put(grammarAccess.getTmlAccess().getMethodsAssignment_4_0_1_3(), "rule__Tml__MethodsAssignment_4_0_1_3");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_4_0_1_4(), "rule__Tml__ChildrenAssignment_4_0_1_4");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_4_0_1_5(), "rule__Tml__ChildrenAssignment_4_0_1_5");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_4_0_1_6(), "rule__Tml__ChildrenAssignment_4_0_1_6");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_4_0_1_7(), "rule__Tml__ChildrenAssignment_4_0_1_7");
					put(grammarAccess.getExpressionAccess().getKeyAssignment_0(), "rule__Expression__KeyAssignment_0");
					put(grammarAccess.getExpressionAccess().getExpressionValueAssignment_3(), "rule__Expression__ExpressionValueAssignment_3");
					put(grammarAccess.getExpressionAccess().getEndTokenAssignment_4(), "rule__Expression__EndTokenAssignment_4");
					put(grammarAccess.getNonExpressionAccess().getNamespaceAssignment_0_0(), "rule__NonExpression__NamespaceAssignment_0_0");
					put(grammarAccess.getNonExpressionAccess().getKeyAssignment_1(), "rule__NonExpression__KeyAssignment_1");
					put(grammarAccess.getMethodsAccess().getMethodAssignment_2_0_1(), "rule__Methods__MethodAssignment_2_0_1");
					put(grammarAccess.getMethodAccess().getNameAttributeAssignment_2_2(), "rule__Method__NameAttributeAssignment_2_2");
					put(grammarAccess.getMethodAccess().getChildrenAssignment_3_0_1(), "rule__Method__ChildrenAssignment_3_0_1");
					put(grammarAccess.getMethodAccess().getClosedTagAssignment_3_0_2(), "rule__Method__ClosedTagAssignment_3_0_2");
					put(grammarAccess.getValidationsAccess().getChildrenAssignment_2_0_1(), "rule__Validations__ChildrenAssignment_2_0_1");
					put(grammarAccess.getValidationsAccess().getClosedTagAssignment_2_0_2(), "rule__Validations__ClosedTagAssignment_2_0_2");
					put(grammarAccess.getCheckAccess().getAttributesAssignment_2(), "rule__Check__AttributesAssignment_2");
					put(grammarAccess.getCheckAccess().getExpressionAssignment_3_0_1(), "rule__Check__ExpressionAssignment_3_0_1");
					put(grammarAccess.getCheckAccess().getClosedTagAssignment_3_0_2(), "rule__Check__ClosedTagAssignment_3_0_2");
					put(grammarAccess.getCommentClauseAccess().getAttributesAssignment_2(), "rule__CommentClause__AttributesAssignment_2");
					put(grammarAccess.getCommentClauseAccess().getClosedTagAssignment_3_0_1(), "rule__CommentClause__ClosedTagAssignment_3_0_1");
					put(grammarAccess.getBreakAccess().getAttributesAssignment_2(), "rule__Break__AttributesAssignment_2");
					put(grammarAccess.getMessageAccess().getCountAssignment_2_0_2(), "rule__Message__CountAssignment_2_0_2");
					put(grammarAccess.getMessageAccess().getModeAssignment_2_1_2(), "rule__Message__ModeAssignment_2_1_2");
					put(grammarAccess.getMessageAccess().getNameAttributeAssignment_2_2_2(), "rule__Message__NameAttributeAssignment_2_2_2");
					put(grammarAccess.getMessageAccess().getTypeAssignment_2_3_2(), "rule__Message__TypeAssignment_2_3_2");
					put(grammarAccess.getMessageAccess().getConditionAssignment_2_4_2(), "rule__Message__ConditionAssignment_2_4_2");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_0(), "rule__Message__ChildrenAssignment_3_0_1_0");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_1(), "rule__Message__ChildrenAssignment_3_0_1_1");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_2(), "rule__Message__ChildrenAssignment_3_0_1_2");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_3(), "rule__Message__ChildrenAssignment_3_0_1_3");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_4(), "rule__Message__ChildrenAssignment_3_0_1_4");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_5(), "rule__Message__ChildrenAssignment_3_0_1_5");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_6(), "rule__Message__ChildrenAssignment_3_0_1_6");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_7(), "rule__Message__ChildrenAssignment_3_0_1_7");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_3_0_1_8(), "rule__Message__ChildrenAssignment_3_0_1_8");
					put(grammarAccess.getMapAccess().getMapNameAssignment_2_1(), "rule__Map__MapNameAssignment_2_1");
					put(grammarAccess.getMapAccess().getRefAssignment_3_0_2(), "rule__Map__RefAssignment_3_0_2");
					put(grammarAccess.getMapAccess().getObjectAssignment_3_1_2(), "rule__Map__ObjectAssignment_3_1_2");
					put(grammarAccess.getMapAccess().getNameAttributeAssignment_3_2_2(), "rule__Map__NameAttributeAssignment_3_2_2");
					put(grammarAccess.getMapAccess().getFilterAssignment_3_3_2(), "rule__Map__FilterAssignment_3_3_2");
					put(grammarAccess.getMapAccess().getExpressionsAssignment_3_4_3(), "rule__Map__ExpressionsAssignment_3_4_3");
					put(grammarAccess.getMapAccess().getConditionAssignment_3_5_2(), "rule__Map__ConditionAssignment_3_5_2");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_0(), "rule__Map__ChildrenAssignment_4_1_1_0");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_1(), "rule__Map__ChildrenAssignment_4_1_1_1");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_2(), "rule__Map__ChildrenAssignment_4_1_1_2");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_3(), "rule__Map__ChildrenAssignment_4_1_1_3");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_4(), "rule__Map__ChildrenAssignment_4_1_1_4");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_5(), "rule__Map__ChildrenAssignment_4_1_1_5");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_6(), "rule__Map__ChildrenAssignment_4_1_1_6");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_7(), "rule__Map__ChildrenAssignment_4_1_1_7");
					put(grammarAccess.getMapAccess().getChildrenAssignment_4_1_1_8(), "rule__Map__ChildrenAssignment_4_1_1_8");
					put(grammarAccess.getMapAccess().getContentAssignment_4_1_1_9(), "rule__Map__ContentAssignment_4_1_1_9");
					put(grammarAccess.getMapAccess().getMapClosingNameAssignment_4_1_3_1(), "rule__Map__MapClosingNameAssignment_4_1_3_1");
					put(grammarAccess.getMapAccess().getClosedTagAssignment_4_1_4(), "rule__Map__ClosedTagAssignment_4_1_4");
					put(grammarAccess.getRequiredAccess().getNameAttributeAssignment_2_2(), "rule__Required__NameAttributeAssignment_2_2");
					put(grammarAccess.getPropertyAccess().getDescriptionAssignment_2_0_2(), "rule__Property__DescriptionAssignment_2_0_2");
					put(grammarAccess.getPropertyAccess().getLengthAssignment_2_1_2(), "rule__Property__LengthAssignment_2_1_2");
					put(grammarAccess.getPropertyAccess().getCardinalityAssignment_2_2_2(), "rule__Property__CardinalityAssignment_2_2_2");
					put(grammarAccess.getPropertyAccess().getDirectionAssignment_2_3_2(), "rule__Property__DirectionAssignment_2_3_2");
					put(grammarAccess.getPropertyAccess().getSubtypesAssignment_2_4_2(), "rule__Property__SubtypesAssignment_2_4_2");
					put(grammarAccess.getPropertyAccess().getNameAttributeAssignment_2_5_2(), "rule__Property__NameAttributeAssignment_2_5_2");
					put(grammarAccess.getPropertyAccess().getTypeAssignment_2_6_2(), "rule__Property__TypeAssignment_2_6_2");
					put(grammarAccess.getPropertyAccess().getConditionAssignment_2_7_2(), "rule__Property__ConditionAssignment_2_7_2");
					put(grammarAccess.getPropertyAccess().getRawValueAssignment_2_8_2(), "rule__Property__RawValueAssignment_2_8_2");
					put(grammarAccess.getPropertyAccess().getChildrenAssignment_3_1_1_0(), "rule__Property__ChildrenAssignment_3_1_1_0");
					put(grammarAccess.getPropertyAccess().getChildrenAssignment_3_1_1_1(), "rule__Property__ChildrenAssignment_3_1_1_1");
					put(grammarAccess.getPropertyAccess().getChildrenAssignment_3_1_1_2(), "rule__Property__ChildrenAssignment_3_1_1_2");
					put(grammarAccess.getParamAccess().getNameAttributeAssignment_2_0_2(), "rule__Param__NameAttributeAssignment_2_0_2");
					put(grammarAccess.getParamAccess().getTypeAssignment_2_1_2(), "rule__Param__TypeAssignment_2_1_2");
					put(grammarAccess.getParamAccess().getConditionAssignment_2_2_2(), "rule__Param__ConditionAssignment_2_2_2");
					put(grammarAccess.getParamAccess().getChildrenAssignment_3_1_1_0(), "rule__Param__ChildrenAssignment_3_1_1_0");
					put(grammarAccess.getParamAccess().getChildrenAssignment_3_1_1_1(), "rule__Param__ChildrenAssignment_3_1_1_1");
					put(grammarAccess.getParamAccess().getChildrenAssignment_3_1_1_2(), "rule__Param__ChildrenAssignment_3_1_1_2");
					put(grammarAccess.getMapMethodAccess().getMapNameAssignment_1(), "rule__MapMethod__MapNameAssignment_1");
					put(grammarAccess.getMapMethodAccess().getMethodNameAssignment_3(), "rule__MapMethod__MethodNameAssignment_3");
					put(grammarAccess.getMapMethodAccess().getAttributesAssignment_4(), "rule__MapMethod__AttributesAssignment_4");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_0(), "rule__MapMethod__ChildrenAssignment_5_1_1_0");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_1(), "rule__MapMethod__ChildrenAssignment_5_1_1_1");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_2(), "rule__MapMethod__ChildrenAssignment_5_1_1_2");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_3(), "rule__MapMethod__ChildrenAssignment_5_1_1_3");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_4(), "rule__MapMethod__ChildrenAssignment_5_1_1_4");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_5(), "rule__MapMethod__ChildrenAssignment_5_1_1_5");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_6(), "rule__MapMethod__ChildrenAssignment_5_1_1_6");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_7(), "rule__MapMethod__ChildrenAssignment_5_1_1_7");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_8(), "rule__MapMethod__ChildrenAssignment_5_1_1_8");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_9(), "rule__MapMethod__ChildrenAssignment_5_1_1_9");
					put(grammarAccess.getMapMethodAccess().getContentAssignment_5_1_1_10(), "rule__MapMethod__ContentAssignment_5_1_1_10");
					put(grammarAccess.getMapMethodAccess().getClosedTagAssignment_5_1_2(), "rule__MapMethod__ClosedTagAssignment_5_1_2");
					put(grammarAccess.getMapMethodAccess().getMethodClosingNameAssignment_5_1_3(), "rule__MapMethod__MethodClosingNameAssignment_5_1_3");
					put(grammarAccess.getMapMethodAccess().getMethodClosingMethodAssignment_5_1_5(), "rule__MapMethod__MethodClosingMethodAssignment_5_1_5");
					put(grammarAccess.getFieldAccess().getNameAttributeAssignment_2_0_2(), "rule__Field__NameAttributeAssignment_2_0_2");
					put(grammarAccess.getFieldAccess().getCommentAssignment_2_1_2(), "rule__Field__CommentAssignment_2_1_2");
					put(grammarAccess.getFieldAccess().getTypeAssignment_2_2_2(), "rule__Field__TypeAssignment_2_2_2");
					put(grammarAccess.getFieldAccess().getConditionAssignment_2_3_2(), "rule__Field__ConditionAssignment_2_3_2");
					put(grammarAccess.getFieldAccess().getFilterAssignment_2_4_2(), "rule__Field__FilterAssignment_2_4_2");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_3_1_0_1_0(), "rule__Field__ChildrenAssignment_3_1_0_1_0");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_3_1_0_1_1(), "rule__Field__ChildrenAssignment_3_1_0_1_1");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_3_1_0_1_2(), "rule__Field__ChildrenAssignment_3_1_0_1_2");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_3_1_0_1_3(), "rule__Field__ChildrenAssignment_3_1_0_1_3");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_3_1_0_1_4(), "rule__Field__ChildrenAssignment_3_1_0_1_4");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_3_1_0_1_5(), "rule__Field__ChildrenAssignment_3_1_0_1_5");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_3_1_0_1_6(), "rule__Field__ChildrenAssignment_3_1_0_1_6");
					put(grammarAccess.getDebugTagAccess().getValueAssignment_2_0_1(), "rule__DebugTag__ValueAssignment_2_0_1");
					put(grammarAccess.getDebugTagAccess().getConditionAssignment_2_1_2(), "rule__DebugTag__ConditionAssignment_2_1_2");
					put(grammarAccess.getDebugTagAccess().getExpressionAssignment_3_1_1(), "rule__DebugTag__ExpressionAssignment_3_1_1");
					put(grammarAccess.getExpressionTagAccess().getValueAssignment_1_0_2(), "rule__ExpressionTag__ValueAssignment_1_0_2");
					put(grammarAccess.getExpressionTagAccess().getConditionAssignment_1_1_2(), "rule__ExpressionTag__ConditionAssignment_1_1_2");
					put(grammarAccess.getExpressionTagAccess().getClosedTagAssignment_2_1_2(), "rule__ExpressionTag__ClosedTagAssignment_2_1_2");
					put(grammarAccess.getOptionAccess().getAttributesAssignment_2(), "rule__Option__AttributesAssignment_2");
					put(grammarAccess.getTopLevelAccess().getToplevelExpressionAssignment(), "rule__TopLevel__ToplevelExpressionAssignment");
					put(grammarAccess.getTmlExpressionAccess().getAbsoluteAssignment_1(), "rule__TmlExpression__AbsoluteAssignment_1");
					put(grammarAccess.getTmlExpressionAccess().getParamAssignment_2(), "rule__TmlExpression__ParamAssignment_2");
					put(grammarAccess.getTmlExpressionAccess().getElementsAssignment_3(), "rule__TmlExpression__ElementsAssignment_3");
					put(grammarAccess.getTmlExpressionAccess().getElementsAssignment_4_1(), "rule__TmlExpression__ElementsAssignment_4_1");
					put(grammarAccess.getExistsTmlExpressionAccess().getAbsoluteAssignment_2(), "rule__ExistsTmlExpression__AbsoluteAssignment_2");
					put(grammarAccess.getExistsTmlExpressionAccess().getParamAssignment_3(), "rule__ExistsTmlExpression__ParamAssignment_3");
					put(grammarAccess.getExistsTmlExpressionAccess().getElementsAssignment_4(), "rule__ExistsTmlExpression__ElementsAssignment_4");
					put(grammarAccess.getExistsTmlExpressionAccess().getElementsAssignment_5_1(), "rule__ExistsTmlExpression__ElementsAssignment_5_1");
					put(grammarAccess.getMapReferenceParamsAccess().getGetterParamsAssignment_1(), "rule__MapReferenceParams__GetterParamsAssignment_1");
					put(grammarAccess.getMapReferenceParamsAccess().getGetterParamsAssignment_2_1(), "rule__MapReferenceParams__GetterParamsAssignment_2_1");
					put(grammarAccess.getMapGetReferenceAccess().getOperationsAssignment_0(), "rule__MapGetReference__OperationsAssignment_0");
					put(grammarAccess.getMapGetReferenceAccess().getElementsAssignment_1_0(), "rule__MapGetReference__ElementsAssignment_1_0");
					put(grammarAccess.getMapGetReferenceAccess().getElementsAssignment_2(), "rule__MapGetReference__ElementsAssignment_2");
					put(grammarAccess.getMapGetReferenceAccess().getReferenceParamsAssignment_3(), "rule__MapGetReference__ReferenceParamsAssignment_3");
					put(grammarAccess.getOrExpressionAccess().getParametersAssignment_0(), "rule__OrExpression__ParametersAssignment_0");
					put(grammarAccess.getOrExpressionAccess().getOperationsAssignment_1_0(), "rule__OrExpression__OperationsAssignment_1_0");
					put(grammarAccess.getOrExpressionAccess().getParametersAssignment_1_1(), "rule__OrExpression__ParametersAssignment_1_1");
					put(grammarAccess.getAndExpressionAccess().getParametersAssignment_0(), "rule__AndExpression__ParametersAssignment_0");
					put(grammarAccess.getAndExpressionAccess().getOperationsAssignment_1_0(), "rule__AndExpression__OperationsAssignment_1_0");
					put(grammarAccess.getAndExpressionAccess().getParametersAssignment_1_1(), "rule__AndExpression__ParametersAssignment_1_1");
					put(grammarAccess.getEqualityExpressionAccess().getParametersAssignment_0(), "rule__EqualityExpression__ParametersAssignment_0");
					put(grammarAccess.getEqualityExpressionAccess().getOperationsAssignment_1_0_0(), "rule__EqualityExpression__OperationsAssignment_1_0_0");
					put(grammarAccess.getEqualityExpressionAccess().getParametersAssignment_1_0_1(), "rule__EqualityExpression__ParametersAssignment_1_0_1");
					put(grammarAccess.getEqualityExpressionAccess().getOperationsAssignment_1_1_0(), "rule__EqualityExpression__OperationsAssignment_1_1_0");
					put(grammarAccess.getEqualityExpressionAccess().getParametersAssignment_1_1_1(), "rule__EqualityExpression__ParametersAssignment_1_1_1");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_1(), "rule__RelationalExpression__ParametersAssignment_1");
					put(grammarAccess.getRelationalExpressionAccess().getOperationsAssignment_2_0_0(), "rule__RelationalExpression__OperationsAssignment_2_0_0");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_2_0_1(), "rule__RelationalExpression__ParametersAssignment_2_0_1");
					put(grammarAccess.getRelationalExpressionAccess().getOperationsAssignment_2_1_0(), "rule__RelationalExpression__OperationsAssignment_2_1_0");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_2_1_1(), "rule__RelationalExpression__ParametersAssignment_2_1_1");
					put(grammarAccess.getRelationalExpressionAccess().getOperationsAssignment_2_2_0(), "rule__RelationalExpression__OperationsAssignment_2_2_0");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_2_2_1(), "rule__RelationalExpression__ParametersAssignment_2_2_1");
					put(grammarAccess.getRelationalExpressionAccess().getOperationsAssignment_2_3_0(), "rule__RelationalExpression__OperationsAssignment_2_3_0");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_2_3_1(), "rule__RelationalExpression__ParametersAssignment_2_3_1");
					put(grammarAccess.getAdditiveExpressionAccess().getParametersAssignment_0(), "rule__AdditiveExpression__ParametersAssignment_0");
					put(grammarAccess.getAdditiveExpressionAccess().getParametersAssignment_1_0_1(), "rule__AdditiveExpression__ParametersAssignment_1_0_1");
					put(grammarAccess.getAdditiveExpressionAccess().getParametersAssignment_1_1_1(), "rule__AdditiveExpression__ParametersAssignment_1_1_1");
					put(grammarAccess.getMultiplicativeExpressionAccess().getParametersAssignment_0(), "rule__MultiplicativeExpression__ParametersAssignment_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getOperationsAssignment_1_0_0(), "rule__MultiplicativeExpression__OperationsAssignment_1_0_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getParametersAssignment_1_0_1(), "rule__MultiplicativeExpression__ParametersAssignment_1_0_1");
					put(grammarAccess.getMultiplicativeExpressionAccess().getOperationsAssignment_1_1_0(), "rule__MultiplicativeExpression__OperationsAssignment_1_1_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getParametersAssignment_1_1_1(), "rule__MultiplicativeExpression__ParametersAssignment_1_1_1");
					put(grammarAccess.getUnaryExpressionAccess().getParametersAssignment_0_0_1(), "rule__UnaryExpression__ParametersAssignment_0_0_1");
					put(grammarAccess.getUnaryExpressionAccess().getParametersAssignment_0_1_1(), "rule__UnaryExpression__ParametersAssignment_0_1_1");
					put(grammarAccess.getPrimaryExpressionAccess().getParametersAssignment_0(), "rule__PrimaryExpression__ParametersAssignment_0");
					put(grammarAccess.getPrimaryExpressionAccess().getParametersAssignment_1_1(), "rule__PrimaryExpression__ParametersAssignment_1_1");
					put(grammarAccess.getFunctionCallAccess().getNameAssignment_0(), "rule__FunctionCall__NameAssignment_0");
					put(grammarAccess.getFunctionCallAccess().getParametersAssignment_2(), "rule__FunctionCall__ParametersAssignment_2");
					put(grammarAccess.getFunctionCallAccess().getParametersAssignment_3_1(), "rule__FunctionCall__ParametersAssignment_3_1");
					put(grammarAccess.getLiteralAccess().getValueStringAssignment_1(), "rule__Literal__ValueStringAssignment_1");
					put(grammarAccess.getLiteralAccess().getOperationsAssignment_2_0(), "rule__Literal__OperationsAssignment_2_0");
					put(grammarAccess.getLiteralAccess().getValueStringAssignment_2_2(), "rule__Literal__ValueStringAssignment_2_2");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_2_4(), "rule__Literal__ParametersAssignment_2_4");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_3(), "rule__Literal__ParametersAssignment_3");
					put(grammarAccess.getLiteralAccess().getExpressionTypeAssignment_4_0(), "rule__Literal__ExpressionTypeAssignment_4_0");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_4_1(), "rule__Literal__ParametersAssignment_4_1");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_4_2_1(), "rule__Literal__ParametersAssignment_4_2_1");
					put(grammarAccess.getLiteralAccess().getElementsAssignment_5(), "rule__Literal__ElementsAssignment_5");
					put(grammarAccess.getLiteralAccess().getElementsAssignment_6(), "rule__Literal__ElementsAssignment_6");
					put(grammarAccess.getLiteralAccess().getElementsAssignment_7(), "rule__Literal__ElementsAssignment_7");
					put(grammarAccess.getLiteralAccess().getElementsAssignment_8(), "rule__Literal__ElementsAssignment_8");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_9(), "rule__Literal__ParametersAssignment_9");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_10(), "rule__Literal__ParametersAssignment_10");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_11(), "rule__Literal__ParametersAssignment_11");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_12(), "rule__Literal__ParametersAssignment_12");
					put(grammarAccess.getTmlAccess().getUnorderedGroup_3(), "rule__Tml__UnorderedGroup_3");
					put(grammarAccess.getMessageAccess().getUnorderedGroup_2(), "rule__Message__UnorderedGroup_2");
					put(grammarAccess.getMapAccess().getUnorderedGroup_3(), "rule__Map__UnorderedGroup_3");
					put(grammarAccess.getPropertyAccess().getUnorderedGroup_2(), "rule__Property__UnorderedGroup_2");
					put(grammarAccess.getParamAccess().getUnorderedGroup_2(), "rule__Param__UnorderedGroup_2");
					put(grammarAccess.getFieldAccess().getUnorderedGroup_2(), "rule__Field__UnorderedGroup_2");
					put(grammarAccess.getExpressionTagAccess().getUnorderedGroup_1(), "rule__ExpressionTag__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser typedParser = (com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser) parser;
			typedParser.entryRuleTml();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_XMLCOMMENT" };
	}
	
	public TslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
