/*
* generated by Xtext
*/
package com.dexels.navajo.dsl.tsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.dexels.navajo.dsl.tsl.services.TslGrammarAccess;

public class TslParser extends AbstractContentAssistParser {
	
	@Inject
	private TslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser createParser() {
		com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser result = new com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTmlAccess().getAlternatives_3(), "rule__Tml__Alternatives_3");
					put(grammarAccess.getTmlAccess().getAlternatives_5(), "rule__Tml__Alternatives_5");
					put(grammarAccess.getTmlAccess().getAlternatives_5_0_1(), "rule__Tml__Alternatives_5_0_1");
					put(grammarAccess.getGarbageAccess().getAlternatives(), "rule__Garbage__Alternatives");
					put(grammarAccess.getMethodsAccess().getAlternatives_3(), "rule__Methods__Alternatives_3");
					put(grammarAccess.getMethodAccess().getAlternatives_4(), "rule__Method__Alternatives_4");
					put(grammarAccess.getValidationsAccess().getAlternatives_3(), "rule__Validations__Alternatives_3");
					put(grammarAccess.getCheckAccess().getAlternatives_4(), "rule__Check__Alternatives_4");
					put(grammarAccess.getCommentClauseAccess().getAlternatives_4(), "rule__CommentClause__Alternatives_4");
					put(grammarAccess.getBreakAccess().getAlternatives_4(), "rule__Break__Alternatives_4");
					put(grammarAccess.getFilePathAccess().getAlternatives(), "rule__FilePath__Alternatives");
					put(grammarAccess.getIncludeAccess().getAlternatives_4(), "rule__Include__Alternatives_4");
					put(grammarAccess.getMessageAccess().getAlternatives_4(), "rule__Message__Alternatives_4");
					put(grammarAccess.getMessageAccess().getAlternatives_4_0_1(), "rule__Message__Alternatives_4_0_1");
					put(grammarAccess.getMapAccess().getAlternatives_5(), "rule__Map__Alternatives_5");
					put(grammarAccess.getMapAccess().getAlternatives_5_1_1(), "rule__Map__Alternatives_5_1_1");
					put(grammarAccess.getRequiredAccess().getAlternatives_4(), "rule__Required__Alternatives_4");
					put(grammarAccess.getPropertyAccess().getAlternatives_4(), "rule__Property__Alternatives_4");
					put(grammarAccess.getPropertyAccess().getAlternatives_4_1_1(), "rule__Property__Alternatives_4_1_1");
					put(grammarAccess.getParamAccess().getAlternatives_4(), "rule__Param__Alternatives_4");
					put(grammarAccess.getParamAccess().getAlternatives_4_1_1(), "rule__Param__Alternatives_4_1_1");
					put(grammarAccess.getMapMethodAccess().getAlternatives_5(), "rule__MapMethod__Alternatives_5");
					put(grammarAccess.getMapMethodAccess().getAlternatives_5_1_1(), "rule__MapMethod__Alternatives_5_1_1");
					put(grammarAccess.getFieldAccess().getAlternatives_4(), "rule__Field__Alternatives_4");
					put(grammarAccess.getFieldAccess().getAlternatives_4_1_0_1(), "rule__Field__Alternatives_4_1_0_1");
					put(grammarAccess.getDebugTagAccess().getAlternatives_4(), "rule__DebugTag__Alternatives_4");
					put(grammarAccess.getExpressionOrOptionAccess().getAlternatives(), "rule__ExpressionOrOption__Alternatives");
					put(grammarAccess.getExpressionTagAccess().getAlternatives_2(), "rule__ExpressionTag__Alternatives_2");
					put(grammarAccess.getOptionAccess().getAlternatives_4(), "rule__Option__Alternatives_4");
					put(grammarAccess.getAnyExpressionAccess().getAlternatives(), "rule__AnyExpression__Alternatives");
					put(grammarAccess.getPathElementAccess().getAlternatives(), "rule__PathElement__Alternatives");
					put(grammarAccess.getEqualityExpressionAccess().getAlternatives_1(), "rule__EqualityExpression__Alternatives_1");
					put(grammarAccess.getRelationalExpressionAccess().getAlternatives_2(), "rule__RelationalExpression__Alternatives_2");
					put(grammarAccess.getAdditiveExpressionAccess().getAlternatives_1(), "rule__AdditiveExpression__Alternatives_1");
					put(grammarAccess.getMultiplicativeExpressionAccess().getAlternatives_1(), "rule__MultiplicativeExpression__Alternatives_1");
					put(grammarAccess.getUnaryExpressionAccess().getAlternatives(), "rule__UnaryExpression__Alternatives");
					put(grammarAccess.getUnaryExpressionAccess().getAlternatives_0(), "rule__UnaryExpression__Alternatives_0");
					put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getTmlAccess().getGroup(), "rule__Tml__Group__0");
					put(grammarAccess.getTmlAccess().getGroup_4_0(), "rule__Tml__Group_4_0__0");
					put(grammarAccess.getTmlAccess().getGroup_4_1(), "rule__Tml__Group_4_1__0");
					put(grammarAccess.getTmlAccess().getGroup_4_2(), "rule__Tml__Group_4_2__0");
					put(grammarAccess.getTmlAccess().getGroup_4_3(), "rule__Tml__Group_4_3__0");
					put(grammarAccess.getTmlAccess().getGroup_4_4(), "rule__Tml__Group_4_4__0");
					put(grammarAccess.getTmlAccess().getGroup_4_5(), "rule__Tml__Group_4_5__0");
					put(grammarAccess.getTmlAccess().getGroup_4_6(), "rule__Tml__Group_4_6__0");
					put(grammarAccess.getTmlAccess().getGroup_4_7(), "rule__Tml__Group_4_7__0");
					put(grammarAccess.getTmlAccess().getGroup_4_8(), "rule__Tml__Group_4_8__0");
					put(grammarAccess.getTmlAccess().getGroup_5_0(), "rule__Tml__Group_5_0__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getNonExpressionAccess().getGroup(), "rule__NonExpression__Group__0");
					put(grammarAccess.getNonExpressionAccess().getGroup_0(), "rule__NonExpression__Group_0__0");
					put(grammarAccess.getNonExpressionAccess().getGroup_3(), "rule__NonExpression__Group_3__0");
					put(grammarAccess.getMethodsAccess().getGroup(), "rule__Methods__Group__0");
					put(grammarAccess.getMethodsAccess().getGroup_3_0(), "rule__Methods__Group_3_0__0");
					put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
					put(grammarAccess.getMethodAccess().getGroup_4_0(), "rule__Method__Group_4_0__0");
					put(grammarAccess.getValidationsAccess().getGroup(), "rule__Validations__Group__0");
					put(grammarAccess.getValidationsAccess().getGroup_3_0(), "rule__Validations__Group_3_0__0");
					put(grammarAccess.getCheckAccess().getGroup(), "rule__Check__Group__0");
					put(grammarAccess.getCheckAccess().getGroup_4_0(), "rule__Check__Group_4_0__0");
					put(grammarAccess.getCommentClauseAccess().getGroup(), "rule__CommentClause__Group__0");
					put(grammarAccess.getCommentClauseAccess().getGroup_4_0(), "rule__CommentClause__Group_4_0__0");
					put(grammarAccess.getBreakAccess().getGroup(), "rule__Break__Group__0");
					put(grammarAccess.getBreakAccess().getGroup_4_0(), "rule__Break__Group_4_0__0");
					put(grammarAccess.getIncludeAccess().getGroup(), "rule__Include__Group__0");
					put(grammarAccess.getIncludeAccess().getGroup_3(), "rule__Include__Group_3__0");
					put(grammarAccess.getIncludeAccess().getGroup_4_0(), "rule__Include__Group_4_0__0");
					put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
					put(grammarAccess.getMessageAccess().getGroup_3_0(), "rule__Message__Group_3_0__0");
					put(grammarAccess.getMessageAccess().getGroup_3_1(), "rule__Message__Group_3_1__0");
					put(grammarAccess.getMessageAccess().getGroup_3_2(), "rule__Message__Group_3_2__0");
					put(grammarAccess.getMessageAccess().getGroup_3_3(), "rule__Message__Group_3_3__0");
					put(grammarAccess.getMessageAccess().getGroup_3_4(), "rule__Message__Group_3_4__0");
					put(grammarAccess.getMessageAccess().getGroup_4_0(), "rule__Message__Group_4_0__0");
					put(grammarAccess.getMapAccess().getGroup(), "rule__Map__Group__0");
					put(grammarAccess.getMapAccess().getGroup_3(), "rule__Map__Group_3__0");
					put(grammarAccess.getMapAccess().getGroup_4_0(), "rule__Map__Group_4_0__0");
					put(grammarAccess.getMapAccess().getGroup_4_1(), "rule__Map__Group_4_1__0");
					put(grammarAccess.getMapAccess().getGroup_4_2(), "rule__Map__Group_4_2__0");
					put(grammarAccess.getMapAccess().getGroup_4_3(), "rule__Map__Group_4_3__0");
					put(grammarAccess.getMapAccess().getGroup_5_1(), "rule__Map__Group_5_1__0");
					put(grammarAccess.getMapAccess().getGroup_5_1_4(), "rule__Map__Group_5_1_4__0");
					put(grammarAccess.getRequiredAccess().getGroup(), "rule__Required__Group__0");
					put(grammarAccess.getRequiredAccess().getGroup_4_1(), "rule__Required__Group_4_1__0");
					put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_0(), "rule__Property__Group_3_0__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_1(), "rule__Property__Group_3_1__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_2(), "rule__Property__Group_3_2__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_3(), "rule__Property__Group_3_3__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_4(), "rule__Property__Group_3_4__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_5(), "rule__Property__Group_3_5__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_6(), "rule__Property__Group_3_6__0");
					put(grammarAccess.getPropertyAccess().getGroup_3_7(), "rule__Property__Group_3_7__0");
					put(grammarAccess.getPropertyAccess().getGroup_4_1(), "rule__Property__Group_4_1__0");
					put(grammarAccess.getParamAccess().getGroup(), "rule__Param__Group__0");
					put(grammarAccess.getParamAccess().getGroup_3_0(), "rule__Param__Group_3_0__0");
					put(grammarAccess.getParamAccess().getGroup_3_1(), "rule__Param__Group_3_1__0");
					put(grammarAccess.getParamAccess().getGroup_3_2(), "rule__Param__Group_3_2__0");
					put(grammarAccess.getParamAccess().getGroup_4_1(), "rule__Param__Group_4_1__0");
					put(grammarAccess.getMapMethodAccess().getGroup(), "rule__MapMethod__Group__0");
					put(grammarAccess.getMapMethodAccess().getGroup_5_1(), "rule__MapMethod__Group_5_1__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getFieldAccess().getGroup_3_0(), "rule__Field__Group_3_0__0");
					put(grammarAccess.getFieldAccess().getGroup_3_1(), "rule__Field__Group_3_1__0");
					put(grammarAccess.getFieldAccess().getGroup_3_2(), "rule__Field__Group_3_2__0");
					put(grammarAccess.getFieldAccess().getGroup_3_3(), "rule__Field__Group_3_3__0");
					put(grammarAccess.getFieldAccess().getGroup_3_4(), "rule__Field__Group_3_4__0");
					put(grammarAccess.getFieldAccess().getGroup_4_1(), "rule__Field__Group_4_1__0");
					put(grammarAccess.getFieldAccess().getGroup_4_1_0(), "rule__Field__Group_4_1_0__0");
					put(grammarAccess.getDebugTagAccess().getGroup(), "rule__DebugTag__Group__0");
					put(grammarAccess.getDebugTagAccess().getGroup_3(), "rule__DebugTag__Group_3__0");
					put(grammarAccess.getDebugTagAccess().getGroup_3_0(), "rule__DebugTag__Group_3_0__0");
					put(grammarAccess.getDebugTagAccess().getGroup_3_1(), "rule__DebugTag__Group_3_1__0");
					put(grammarAccess.getDebugTagAccess().getGroup_4_1(), "rule__DebugTag__Group_4_1__0");
					put(grammarAccess.getExpressionOrOptionAccess().getGroup_0(), "rule__ExpressionOrOption__Group_0__0");
					put(grammarAccess.getExpressionOrOptionAccess().getGroup_1(), "rule__ExpressionOrOption__Group_1__0");
					put(grammarAccess.getExpressionTagAccess().getGroup(), "rule__ExpressionTag__Group__0");
					put(grammarAccess.getExpressionTagAccess().getGroup_1_0(), "rule__ExpressionTag__Group_1_0__0");
					put(grammarAccess.getExpressionTagAccess().getGroup_1_1(), "rule__ExpressionTag__Group_1_1__0");
					put(grammarAccess.getExpressionTagAccess().getGroup_1_2(), "rule__ExpressionTag__Group_1_2__0");
					put(grammarAccess.getExpressionTagAccess().getGroup_2_1(), "rule__ExpressionTag__Group_2_1__0");
					put(grammarAccess.getOptionAccess().getGroup(), "rule__Option__Group__0");
					put(grammarAccess.getOptionAccess().getGroup_4_1(), "rule__Option__Group_4_1__0");
					put(grammarAccess.getTmlExpressionAccess().getGroup(), "rule__TmlExpression__Group__0");
					put(grammarAccess.getTmlExpressionAccess().getGroup_4(), "rule__TmlExpression__Group_4__0");
					put(grammarAccess.getExistsTmlExpressionAccess().getGroup(), "rule__ExistsTmlExpression__Group__0");
					put(grammarAccess.getExistsTmlExpressionAccess().getGroup_5(), "rule__ExistsTmlExpression__Group_5__0");
					put(grammarAccess.getMapReferenceParamsAccess().getGroup(), "rule__MapReferenceParams__Group__0");
					put(grammarAccess.getMapReferenceParamsAccess().getGroup_2(), "rule__MapReferenceParams__Group_2__0");
					put(grammarAccess.getMapGetReferenceAccess().getGroup(), "rule__MapGetReference__Group__0");
					put(grammarAccess.getMapGetReferenceAccess().getGroup_1(), "rule__MapGetReference__Group_1__0");
					put(grammarAccess.getOrExpressionAccess().getGroup(), "rule__OrExpression__Group__0");
					put(grammarAccess.getOrExpressionAccess().getGroup_1(), "rule__OrExpression__Group_1__0");
					put(grammarAccess.getAndExpressionAccess().getGroup(), "rule__AndExpression__Group__0");
					put(grammarAccess.getAndExpressionAccess().getGroup_1(), "rule__AndExpression__Group_1__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup(), "rule__EqualityExpression__Group__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup_1_0(), "rule__EqualityExpression__Group_1_0__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup_1_1(), "rule__EqualityExpression__Group_1_1__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup(), "rule__RelationalExpression__Group__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_2_0(), "rule__RelationalExpression__Group_2_0__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_2_1(), "rule__RelationalExpression__Group_2_1__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_2_2(), "rule__RelationalExpression__Group_2_2__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_2_3(), "rule__RelationalExpression__Group_2_3__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup(), "rule__AdditiveExpression__Group__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup_1_0(), "rule__AdditiveExpression__Group_1_0__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup_1_1(), "rule__AdditiveExpression__Group_1_1__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup(), "rule__MultiplicativeExpression__Group__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1_0(), "rule__MultiplicativeExpression__Group_1_0__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1_1(), "rule__MultiplicativeExpression__Group_1_1__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_0_0(), "rule__UnaryExpression__Group_0_0__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_0_1(), "rule__UnaryExpression__Group_0_1__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_1(), "rule__PrimaryExpression__Group_1__0");
					put(grammarAccess.getFunctionCallAccess().getGroup(), "rule__FunctionCall__Group__0");
					put(grammarAccess.getFunctionCallAccess().getGroup_3(), "rule__FunctionCall__Group_3__0");
					put(grammarAccess.getDateLiteralAccess().getGroup(), "rule__DateLiteral__Group__0");
					put(grammarAccess.getLiteralAccess().getGroup_0(), "rule__Literal__Group_0__0");
					put(grammarAccess.getLiteralAccess().getGroup_2(), "rule__Literal__Group_2__0");
					put(grammarAccess.getLiteralAccess().getGroup_4(), "rule__Literal__Group_4__0");
					put(grammarAccess.getLiteralAccess().getGroup_4_2(), "rule__Literal__Group_4_2__0");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_5_0_1_0(), "rule__Tml__ChildrenAssignment_5_0_1_0");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_5_0_1_1(), "rule__Tml__ChildrenAssignment_5_0_1_1");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_5_0_1_2(), "rule__Tml__ChildrenAssignment_5_0_1_2");
					put(grammarAccess.getTmlAccess().getMethodsAssignment_5_0_1_3(), "rule__Tml__MethodsAssignment_5_0_1_3");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_5_0_1_4(), "rule__Tml__ChildrenAssignment_5_0_1_4");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_5_0_1_5(), "rule__Tml__ChildrenAssignment_5_0_1_5");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_5_0_1_6(), "rule__Tml__ChildrenAssignment_5_0_1_6");
					put(grammarAccess.getTmlAccess().getChildrenAssignment_5_0_1_7(), "rule__Tml__ChildrenAssignment_5_0_1_7");
					put(grammarAccess.getExpressionAccess().getKeyAssignment_0(), "rule__Expression__KeyAssignment_0");
					put(grammarAccess.getExpressionAccess().getExpressionValueAssignment_3(), "rule__Expression__ExpressionValueAssignment_3");
					put(grammarAccess.getExpressionAccess().getEndTokenAssignment_4(), "rule__Expression__EndTokenAssignment_4");
					put(grammarAccess.getNonExpressionAccess().getNamespaceAssignment_0_0(), "rule__NonExpression__NamespaceAssignment_0_0");
					put(grammarAccess.getNonExpressionAccess().getKeyAssignment_1(), "rule__NonExpression__KeyAssignment_1");
					put(grammarAccess.getNonExpressionAccess().getValueAssignment_3_1(), "rule__NonExpression__ValueAssignment_3_1");
					put(grammarAccess.getMethodsAccess().getSplitTagAssignment_3_0_0(), "rule__Methods__SplitTagAssignment_3_0_0");
					put(grammarAccess.getMethodsAccess().getMethodAssignment_3_0_1(), "rule__Methods__MethodAssignment_3_0_1");
					put(grammarAccess.getMethodsAccess().getClosedTagAssignment_3_0_2(), "rule__Methods__ClosedTagAssignment_3_0_2");
					put(grammarAccess.getMethodAccess().getAttributesAssignment_3(), "rule__Method__AttributesAssignment_3");
					put(grammarAccess.getMethodAccess().getSplitTagAssignment_4_0_0(), "rule__Method__SplitTagAssignment_4_0_0");
					put(grammarAccess.getMethodAccess().getChildrenAssignment_4_0_1(), "rule__Method__ChildrenAssignment_4_0_1");
					put(grammarAccess.getMethodAccess().getClosedTagAssignment_4_0_2(), "rule__Method__ClosedTagAssignment_4_0_2");
					put(grammarAccess.getValidationsAccess().getSplitTagAssignment_3_0_0(), "rule__Validations__SplitTagAssignment_3_0_0");
					put(grammarAccess.getValidationsAccess().getChildrenAssignment_3_0_1(), "rule__Validations__ChildrenAssignment_3_0_1");
					put(grammarAccess.getValidationsAccess().getClosedTagAssignment_3_0_2(), "rule__Validations__ClosedTagAssignment_3_0_2");
					put(grammarAccess.getCheckAccess().getAttributesAssignment_3(), "rule__Check__AttributesAssignment_3");
					put(grammarAccess.getCheckAccess().getSplitTagAssignment_4_0_0(), "rule__Check__SplitTagAssignment_4_0_0");
					put(grammarAccess.getCheckAccess().getExpressionAssignment_4_0_1(), "rule__Check__ExpressionAssignment_4_0_1");
					put(grammarAccess.getCheckAccess().getClosedTagAssignment_4_0_2(), "rule__Check__ClosedTagAssignment_4_0_2");
					put(grammarAccess.getCommentClauseAccess().getAttributesAssignment_3(), "rule__CommentClause__AttributesAssignment_3");
					put(grammarAccess.getCommentClauseAccess().getSplitTagAssignment_4_0_0(), "rule__CommentClause__SplitTagAssignment_4_0_0");
					put(grammarAccess.getCommentClauseAccess().getClosedTagAssignment_4_0_1(), "rule__CommentClause__ClosedTagAssignment_4_0_1");
					put(grammarAccess.getBreakAccess().getAttributesAssignment_3(), "rule__Break__AttributesAssignment_3");
					put(grammarAccess.getBreakAccess().getSplitTagAssignment_4_0_0(), "rule__Break__SplitTagAssignment_4_0_0");
					put(grammarAccess.getBreakAccess().getClosedTagAssignment_4_0_1(), "rule__Break__ClosedTagAssignment_4_0_1");
					put(grammarAccess.getIncludeAccess().getPathAssignment_3_3(), "rule__Include__PathAssignment_3_3");
					put(grammarAccess.getIncludeAccess().getSplitTagAssignment_4_0_0(), "rule__Include__SplitTagAssignment_4_0_0");
					put(grammarAccess.getIncludeAccess().getClosedTagAssignment_4_0_1(), "rule__Include__ClosedTagAssignment_4_0_1");
					put(grammarAccess.getMessageAccess().getCountAssignment_3_0_3(), "rule__Message__CountAssignment_3_0_3");
					put(grammarAccess.getMessageAccess().getModeAssignment_3_1_3(), "rule__Message__ModeAssignment_3_1_3");
					put(grammarAccess.getMessageAccess().getNameAttributeAssignment_3_2_3(), "rule__Message__NameAttributeAssignment_3_2_3");
					put(grammarAccess.getMessageAccess().getTypeAssignment_3_3_3(), "rule__Message__TypeAssignment_3_3_3");
					put(grammarAccess.getMessageAccess().getConditionAssignment_3_4_3(), "rule__Message__ConditionAssignment_3_4_3");
					put(grammarAccess.getMessageAccess().getSplitTagAssignment_4_0_0(), "rule__Message__SplitTagAssignment_4_0_0");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_0(), "rule__Message__ChildrenAssignment_4_0_1_0");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_1(), "rule__Message__ChildrenAssignment_4_0_1_1");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_2(), "rule__Message__ChildrenAssignment_4_0_1_2");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_3(), "rule__Message__ChildrenAssignment_4_0_1_3");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_4(), "rule__Message__ChildrenAssignment_4_0_1_4");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_5(), "rule__Message__ChildrenAssignment_4_0_1_5");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_6(), "rule__Message__ChildrenAssignment_4_0_1_6");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_7(), "rule__Message__ChildrenAssignment_4_0_1_7");
					put(grammarAccess.getMessageAccess().getChildrenAssignment_4_0_1_8(), "rule__Message__ChildrenAssignment_4_0_1_8");
					put(grammarAccess.getMessageAccess().getClosedTagAssignment_4_0_3(), "rule__Message__ClosedTagAssignment_4_0_3");
					put(grammarAccess.getMapAccess().getMapNameAssignment_3_1(), "rule__Map__MapNameAssignment_3_1");
					put(grammarAccess.getMapAccess().getRefAssignment_4_0_3(), "rule__Map__RefAssignment_4_0_3");
					put(grammarAccess.getMapAccess().getObjectAssignment_4_1_3(), "rule__Map__ObjectAssignment_4_1_3");
					put(grammarAccess.getMapAccess().getNameAttributeAssignment_4_2_3(), "rule__Map__NameAttributeAssignment_4_2_3");
					put(grammarAccess.getMapAccess().getFilterAssignment_4_3_3(), "rule__Map__FilterAssignment_4_3_3");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_0(), "rule__Map__ChildrenAssignment_5_1_1_0");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_1(), "rule__Map__ChildrenAssignment_5_1_1_1");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_2(), "rule__Map__ChildrenAssignment_5_1_1_2");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_3(), "rule__Map__ChildrenAssignment_5_1_1_3");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_4(), "rule__Map__ChildrenAssignment_5_1_1_4");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_5(), "rule__Map__ChildrenAssignment_5_1_1_5");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_6(), "rule__Map__ChildrenAssignment_5_1_1_6");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_7(), "rule__Map__ChildrenAssignment_5_1_1_7");
					put(grammarAccess.getMapAccess().getChildrenAssignment_5_1_1_8(), "rule__Map__ChildrenAssignment_5_1_1_8");
					put(grammarAccess.getMapAccess().getMapClosingNameAssignment_5_1_4_1(), "rule__Map__MapClosingNameAssignment_5_1_4_1");
					put(grammarAccess.getMapAccess().getClosedTagAssignment_5_1_5(), "rule__Map__ClosedTagAssignment_5_1_5");
					put(grammarAccess.getRequiredAccess().getAttributesAssignment_3(), "rule__Required__AttributesAssignment_3");
					put(grammarAccess.getRequiredAccess().getSplitTagAssignment_4_1_0(), "rule__Required__SplitTagAssignment_4_1_0");
					put(grammarAccess.getRequiredAccess().getClosedTagAssignment_4_1_1(), "rule__Required__ClosedTagAssignment_4_1_1");
					put(grammarAccess.getPropertyAccess().getDescriptionAssignment_3_0_3(), "rule__Property__DescriptionAssignment_3_0_3");
					put(grammarAccess.getPropertyAccess().getLengthAssignment_3_1_3(), "rule__Property__LengthAssignment_3_1_3");
					put(grammarAccess.getPropertyAccess().getCardinalityAssignment_3_2_3(), "rule__Property__CardinalityAssignment_3_2_3");
					put(grammarAccess.getPropertyAccess().getDirectionAssignment_3_3_3(), "rule__Property__DirectionAssignment_3_3_3");
					put(grammarAccess.getPropertyAccess().getSubtypesAssignment_3_4_3(), "rule__Property__SubtypesAssignment_3_4_3");
					put(grammarAccess.getPropertyAccess().getNameAttributeAssignment_3_5_3(), "rule__Property__NameAttributeAssignment_3_5_3");
					put(grammarAccess.getPropertyAccess().getTypeAssignment_3_6_3(), "rule__Property__TypeAssignment_3_6_3");
					put(grammarAccess.getPropertyAccess().getConditionAssignment_3_7_3(), "rule__Property__ConditionAssignment_3_7_3");
					put(grammarAccess.getPropertyAccess().getSplitTagAssignment_4_1_0(), "rule__Property__SplitTagAssignment_4_1_0");
					put(grammarAccess.getPropertyAccess().getChildrenAssignment_4_1_1_0(), "rule__Property__ChildrenAssignment_4_1_1_0");
					put(grammarAccess.getPropertyAccess().getChildrenAssignment_4_1_1_1(), "rule__Property__ChildrenAssignment_4_1_1_1");
					put(grammarAccess.getPropertyAccess().getClosedTagAssignment_4_1_2(), "rule__Property__ClosedTagAssignment_4_1_2");
					put(grammarAccess.getParamAccess().getNameAttributeAssignment_3_0_3(), "rule__Param__NameAttributeAssignment_3_0_3");
					put(grammarAccess.getParamAccess().getTypeAssignment_3_1_3(), "rule__Param__TypeAssignment_3_1_3");
					put(grammarAccess.getParamAccess().getConditionAssignment_3_2_3(), "rule__Param__ConditionAssignment_3_2_3");
					put(grammarAccess.getParamAccess().getSplitTagAssignment_4_1_0(), "rule__Param__SplitTagAssignment_4_1_0");
					put(grammarAccess.getParamAccess().getChildrenAssignment_4_1_1_0(), "rule__Param__ChildrenAssignment_4_1_1_0");
					put(grammarAccess.getParamAccess().getChildrenAssignment_4_1_1_1(), "rule__Param__ChildrenAssignment_4_1_1_1");
					put(grammarAccess.getParamAccess().getClosedTagAssignment_4_1_3(), "rule__Param__ClosedTagAssignment_4_1_3");
					put(grammarAccess.getMapMethodAccess().getMapNameAssignment_1(), "rule__MapMethod__MapNameAssignment_1");
					put(grammarAccess.getMapMethodAccess().getMethodNameAssignment_3(), "rule__MapMethod__MethodNameAssignment_3");
					put(grammarAccess.getMapMethodAccess().getAttributesAssignment_4(), "rule__MapMethod__AttributesAssignment_4");
					put(grammarAccess.getMapMethodAccess().getSplitTagAssignment_5_1_0(), "rule__MapMethod__SplitTagAssignment_5_1_0");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_0(), "rule__MapMethod__ChildrenAssignment_5_1_1_0");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_1(), "rule__MapMethod__ChildrenAssignment_5_1_1_1");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_2(), "rule__MapMethod__ChildrenAssignment_5_1_1_2");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_3(), "rule__MapMethod__ChildrenAssignment_5_1_1_3");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_4(), "rule__MapMethod__ChildrenAssignment_5_1_1_4");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_5(), "rule__MapMethod__ChildrenAssignment_5_1_1_5");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_6(), "rule__MapMethod__ChildrenAssignment_5_1_1_6");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_7(), "rule__MapMethod__ChildrenAssignment_5_1_1_7");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_8(), "rule__MapMethod__ChildrenAssignment_5_1_1_8");
					put(grammarAccess.getMapMethodAccess().getChildrenAssignment_5_1_1_9(), "rule__MapMethod__ChildrenAssignment_5_1_1_9");
					put(grammarAccess.getMapMethodAccess().getClosedTagAssignment_5_1_2(), "rule__MapMethod__ClosedTagAssignment_5_1_2");
					put(grammarAccess.getMapMethodAccess().getMethodClosingNameAssignment_5_1_3(), "rule__MapMethod__MethodClosingNameAssignment_5_1_3");
					put(grammarAccess.getMapMethodAccess().getMethodClosingMethodAssignment_5_1_5(), "rule__MapMethod__MethodClosingMethodAssignment_5_1_5");
					put(grammarAccess.getFieldAccess().getNameAttributeAssignment_3_0_3(), "rule__Field__NameAttributeAssignment_3_0_3");
					put(grammarAccess.getFieldAccess().getCommentAssignment_3_1_3(), "rule__Field__CommentAssignment_3_1_3");
					put(grammarAccess.getFieldAccess().getTypeAssignment_3_2_3(), "rule__Field__TypeAssignment_3_2_3");
					put(grammarAccess.getFieldAccess().getConditionAssignment_3_3_3(), "rule__Field__ConditionAssignment_3_3_3");
					put(grammarAccess.getFieldAccess().getFilterAssignment_3_4_3(), "rule__Field__FilterAssignment_3_4_3");
					put(grammarAccess.getFieldAccess().getSplitTagAssignment_4_1_0_0(), "rule__Field__SplitTagAssignment_4_1_0_0");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_4_1_0_1_0(), "rule__Field__ChildrenAssignment_4_1_0_1_0");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_4_1_0_1_1(), "rule__Field__ChildrenAssignment_4_1_0_1_1");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_4_1_0_1_2(), "rule__Field__ChildrenAssignment_4_1_0_1_2");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_4_1_0_1_3(), "rule__Field__ChildrenAssignment_4_1_0_1_3");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_4_1_0_1_4(), "rule__Field__ChildrenAssignment_4_1_0_1_4");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_4_1_0_1_5(), "rule__Field__ChildrenAssignment_4_1_0_1_5");
					put(grammarAccess.getFieldAccess().getChildrenAssignment_4_1_0_1_6(), "rule__Field__ChildrenAssignment_4_1_0_1_6");
					put(grammarAccess.getFieldAccess().getClosedTagAssignment_4_1_2(), "rule__Field__ClosedTagAssignment_4_1_2");
					put(grammarAccess.getDebugTagAccess().getValueAssignment_3_0_2(), "rule__DebugTag__ValueAssignment_3_0_2");
					put(grammarAccess.getDebugTagAccess().getConditionAssignment_3_1_3(), "rule__DebugTag__ConditionAssignment_3_1_3");
					put(grammarAccess.getDebugTagAccess().getSplitTagAssignment_4_1_0(), "rule__DebugTag__SplitTagAssignment_4_1_0");
					put(grammarAccess.getDebugTagAccess().getExpressionAssignment_4_1_1(), "rule__DebugTag__ExpressionAssignment_4_1_1");
					put(grammarAccess.getDebugTagAccess().getClosedTagAssignment_4_1_3(), "rule__DebugTag__ClosedTagAssignment_4_1_3");
					put(grammarAccess.getExpressionTagAccess().getValueAssignment_1_0_3(), "rule__ExpressionTag__ValueAssignment_1_0_3");
					put(grammarAccess.getExpressionTagAccess().getConditionAssignment_1_1_3(), "rule__ExpressionTag__ConditionAssignment_1_1_3");
					put(grammarAccess.getExpressionTagAccess().getSplitTagAssignment_2_1_0(), "rule__ExpressionTag__SplitTagAssignment_2_1_0");
					put(grammarAccess.getExpressionTagAccess().getContentAssignment_2_1_1(), "rule__ExpressionTag__ContentAssignment_2_1_1");
					put(grammarAccess.getExpressionTagAccess().getClosedTagAssignment_2_1_2(), "rule__ExpressionTag__ClosedTagAssignment_2_1_2");
					put(grammarAccess.getOptionAccess().getAttributesAssignment_3(), "rule__Option__AttributesAssignment_3");
					put(grammarAccess.getOptionAccess().getSplitTagAssignment_4_1_0(), "rule__Option__SplitTagAssignment_4_1_0");
					put(grammarAccess.getOptionAccess().getClosedTagAssignment_4_1_2(), "rule__Option__ClosedTagAssignment_4_1_2");
					put(grammarAccess.getTopLevelAccess().getToplevelExpressionAssignment(), "rule__TopLevel__ToplevelExpressionAssignment");
					put(grammarAccess.getTmlExpressionAccess().getAbsoluteAssignment_1(), "rule__TmlExpression__AbsoluteAssignment_1");
					put(grammarAccess.getTmlExpressionAccess().getParamAssignment_2(), "rule__TmlExpression__ParamAssignment_2");
					put(grammarAccess.getTmlExpressionAccess().getElementsAssignment_3(), "rule__TmlExpression__ElementsAssignment_3");
					put(grammarAccess.getTmlExpressionAccess().getElementsAssignment_4_1(), "rule__TmlExpression__ElementsAssignment_4_1");
					put(grammarAccess.getExistsTmlExpressionAccess().getAbsoluteAssignment_2(), "rule__ExistsTmlExpression__AbsoluteAssignment_2");
					put(grammarAccess.getExistsTmlExpressionAccess().getParamAssignment_3(), "rule__ExistsTmlExpression__ParamAssignment_3");
					put(grammarAccess.getExistsTmlExpressionAccess().getElementsAssignment_4(), "rule__ExistsTmlExpression__ElementsAssignment_4");
					put(grammarAccess.getExistsTmlExpressionAccess().getElementsAssignment_5_1(), "rule__ExistsTmlExpression__ElementsAssignment_5_1");
					put(grammarAccess.getMapReferenceParamsAccess().getGetterParamsAssignment_1(), "rule__MapReferenceParams__GetterParamsAssignment_1");
					put(grammarAccess.getMapReferenceParamsAccess().getGetterParamsAssignment_2_1(), "rule__MapReferenceParams__GetterParamsAssignment_2_1");
					put(grammarAccess.getMapGetReferenceAccess().getOperationsAssignment_0(), "rule__MapGetReference__OperationsAssignment_0");
					put(grammarAccess.getMapGetReferenceAccess().getElementsAssignment_1_0(), "rule__MapGetReference__ElementsAssignment_1_0");
					put(grammarAccess.getMapGetReferenceAccess().getElementsAssignment_2(), "rule__MapGetReference__ElementsAssignment_2");
					put(grammarAccess.getMapGetReferenceAccess().getReferenceParamsAssignment_3(), "rule__MapGetReference__ReferenceParamsAssignment_3");
					put(grammarAccess.getOrExpressionAccess().getParametersAssignment_0(), "rule__OrExpression__ParametersAssignment_0");
					put(grammarAccess.getOrExpressionAccess().getOperationsAssignment_1_0(), "rule__OrExpression__OperationsAssignment_1_0");
					put(grammarAccess.getOrExpressionAccess().getParametersAssignment_1_1(), "rule__OrExpression__ParametersAssignment_1_1");
					put(grammarAccess.getAndExpressionAccess().getParametersAssignment_0(), "rule__AndExpression__ParametersAssignment_0");
					put(grammarAccess.getAndExpressionAccess().getOperationsAssignment_1_0(), "rule__AndExpression__OperationsAssignment_1_0");
					put(grammarAccess.getAndExpressionAccess().getParametersAssignment_1_1(), "rule__AndExpression__ParametersAssignment_1_1");
					put(grammarAccess.getEqualityExpressionAccess().getParametersAssignment_0(), "rule__EqualityExpression__ParametersAssignment_0");
					put(grammarAccess.getEqualityExpressionAccess().getOperationsAssignment_1_0_0(), "rule__EqualityExpression__OperationsAssignment_1_0_0");
					put(grammarAccess.getEqualityExpressionAccess().getParametersAssignment_1_0_1(), "rule__EqualityExpression__ParametersAssignment_1_0_1");
					put(grammarAccess.getEqualityExpressionAccess().getOperationsAssignment_1_1_0(), "rule__EqualityExpression__OperationsAssignment_1_1_0");
					put(grammarAccess.getEqualityExpressionAccess().getParametersAssignment_1_1_1(), "rule__EqualityExpression__ParametersAssignment_1_1_1");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_1(), "rule__RelationalExpression__ParametersAssignment_1");
					put(grammarAccess.getRelationalExpressionAccess().getOperationsAssignment_2_0_0(), "rule__RelationalExpression__OperationsAssignment_2_0_0");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_2_0_1(), "rule__RelationalExpression__ParametersAssignment_2_0_1");
					put(grammarAccess.getRelationalExpressionAccess().getOperationsAssignment_2_1_0(), "rule__RelationalExpression__OperationsAssignment_2_1_0");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_2_1_1(), "rule__RelationalExpression__ParametersAssignment_2_1_1");
					put(grammarAccess.getRelationalExpressionAccess().getOperationsAssignment_2_2_0(), "rule__RelationalExpression__OperationsAssignment_2_2_0");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_2_2_1(), "rule__RelationalExpression__ParametersAssignment_2_2_1");
					put(grammarAccess.getRelationalExpressionAccess().getOperationsAssignment_2_3_0(), "rule__RelationalExpression__OperationsAssignment_2_3_0");
					put(grammarAccess.getRelationalExpressionAccess().getParametersAssignment_2_3_1(), "rule__RelationalExpression__ParametersAssignment_2_3_1");
					put(grammarAccess.getAdditiveExpressionAccess().getParametersAssignment_0(), "rule__AdditiveExpression__ParametersAssignment_0");
					put(grammarAccess.getAdditiveExpressionAccess().getParametersAssignment_1_0_1(), "rule__AdditiveExpression__ParametersAssignment_1_0_1");
					put(grammarAccess.getAdditiveExpressionAccess().getParametersAssignment_1_1_1(), "rule__AdditiveExpression__ParametersAssignment_1_1_1");
					put(grammarAccess.getMultiplicativeExpressionAccess().getParametersAssignment_0(), "rule__MultiplicativeExpression__ParametersAssignment_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getOperationsAssignment_1_0_0(), "rule__MultiplicativeExpression__OperationsAssignment_1_0_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getParametersAssignment_1_0_1(), "rule__MultiplicativeExpression__ParametersAssignment_1_0_1");
					put(grammarAccess.getMultiplicativeExpressionAccess().getOperationsAssignment_1_1_0(), "rule__MultiplicativeExpression__OperationsAssignment_1_1_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getParametersAssignment_1_1_1(), "rule__MultiplicativeExpression__ParametersAssignment_1_1_1");
					put(grammarAccess.getUnaryExpressionAccess().getParametersAssignment_0_0_1(), "rule__UnaryExpression__ParametersAssignment_0_0_1");
					put(grammarAccess.getUnaryExpressionAccess().getParametersAssignment_0_1_1(), "rule__UnaryExpression__ParametersAssignment_0_1_1");
					put(grammarAccess.getPrimaryExpressionAccess().getParametersAssignment_0(), "rule__PrimaryExpression__ParametersAssignment_0");
					put(grammarAccess.getPrimaryExpressionAccess().getParametersAssignment_1_1(), "rule__PrimaryExpression__ParametersAssignment_1_1");
					put(grammarAccess.getFunctionCallAccess().getNameAssignment_0(), "rule__FunctionCall__NameAssignment_0");
					put(grammarAccess.getFunctionCallAccess().getParametersAssignment_2(), "rule__FunctionCall__ParametersAssignment_2");
					put(grammarAccess.getFunctionCallAccess().getParametersAssignment_3_1(), "rule__FunctionCall__ParametersAssignment_3_1");
					put(grammarAccess.getLiteralAccess().getValueStringAssignment_1(), "rule__Literal__ValueStringAssignment_1");
					put(grammarAccess.getLiteralAccess().getOperationsAssignment_2_0(), "rule__Literal__OperationsAssignment_2_0");
					put(grammarAccess.getLiteralAccess().getValueStringAssignment_2_2(), "rule__Literal__ValueStringAssignment_2_2");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_2_4(), "rule__Literal__ParametersAssignment_2_4");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_3(), "rule__Literal__ParametersAssignment_3");
					put(grammarAccess.getLiteralAccess().getExpressionTypeAssignment_4_0(), "rule__Literal__ExpressionTypeAssignment_4_0");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_4_1(), "rule__Literal__ParametersAssignment_4_1");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_4_2_1(), "rule__Literal__ParametersAssignment_4_2_1");
					put(grammarAccess.getLiteralAccess().getElementsAssignment_5(), "rule__Literal__ElementsAssignment_5");
					put(grammarAccess.getLiteralAccess().getElementsAssignment_6(), "rule__Literal__ElementsAssignment_6");
					put(grammarAccess.getLiteralAccess().getElementsAssignment_7(), "rule__Literal__ElementsAssignment_7");
					put(grammarAccess.getLiteralAccess().getElementsAssignment_8(), "rule__Literal__ElementsAssignment_8");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_9(), "rule__Literal__ParametersAssignment_9");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_10(), "rule__Literal__ParametersAssignment_10");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_11(), "rule__Literal__ParametersAssignment_11");
					put(grammarAccess.getLiteralAccess().getParametersAssignment_12(), "rule__Literal__ParametersAssignment_12");
					put(grammarAccess.getTmlAccess().getUnorderedGroup_4(), "rule__Tml__UnorderedGroup_4");
					put(grammarAccess.getMessageAccess().getUnorderedGroup_3(), "rule__Message__UnorderedGroup_3");
					put(grammarAccess.getMapAccess().getUnorderedGroup_4(), "rule__Map__UnorderedGroup_4");
					put(grammarAccess.getPropertyAccess().getUnorderedGroup_3(), "rule__Property__UnorderedGroup_3");
					put(grammarAccess.getParamAccess().getUnorderedGroup_3(), "rule__Param__UnorderedGroup_3");
					put(grammarAccess.getFieldAccess().getUnorderedGroup_3(), "rule__Field__UnorderedGroup_3");
					put(grammarAccess.getExpressionTagAccess().getUnorderedGroup_1(), "rule__ExpressionTag__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser typedParser = (com.dexels.navajo.dsl.tsl.ui.contentassist.antlr.internal.InternalTslParser) parser;
			typedParser.entryRuleTml();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_XMLCOMMENT" };
	}
	
	public TslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
