/*
 * generated by Xtext
 */
package com.dexels.navajo.dsl.expression.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.dexels.navajo.dsl.expression.ui.internal.NavajoExpressionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NavajoExpressionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return NavajoExpressionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return NavajoExpressionActivator.getInstance().getInjector(NavajoExpressionActivator.COM_DEXELS_NAVAJO_DSL_EXPRESSION_NAVAJOEXPRESSION);
	}
	
}
